export const moduleRegistry = {
  bio: { label: "Bio", icon: "person", premium: false },
  links: { label: "Unlimited Links", icon: "link", premium: false },
  whatsapp: { label: "WhatsApp CTA", icon: "chat", premium: false },
  vcard: { label: "vCard", icon: "contact-page", premium: false },
  payments: { label: "Payments", icon: "payments", premium: true },
  shop: { label: "Shop", icon: "storefront", premium: true },
  analytics: { label: "Analytics", icon: "query-stats", premium: true },
  petInfo: { label: "Pet Info", icon: "pets", premium: false },
  ownerContact: { label: "Owner Contact", icon: "call", premium: false },
  vaccination: { label: "Vaccination", icon: "vaccines", premium: false },
  reward: { label: "Reward", icon: "redeem", premium: false },
  finderChat: { label: "Finder Chat", icon: "forum", premium: true },
  liveLocation: { label: "Live Location", icon: "my-location", premium: true },
  vehicleDocs: { label: "Vehicle Docs", icon: "description", premium: false },
  fastag: { label: "FASTag", icon: "local-offer", premium: false },
  roadsideHelp: { label: "Roadside Help", icon: "support-agent", premium: false },
  sos: { label: "SOS", icon: "sos", premium: false },
  emergencyContacts: { label: "Emergency Contacts", icon: "health-and-safety", premium: false },
  assetId: { label: "Asset ID", icon: "inventory", premium: false },
  scanHeatmap: { label: "Scan Heatmap", icon: "map", premium: true },
  leadCapture: { label: "Lead Capture", icon: "fact-check", premium: true },
  appointments: { label: "Appointments", icon: "event", premium: true },
  catalog: { label: "Catalog", icon: "category", premium: true }
};
